import { useEffect, useRef, useState } from 'react';
import { Alert, Button, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as SecureStore from 'expo-secure-store';
import * as Location from 'expo-location';

const API = process.env.EXPO_PUBLIC_API_URL ?? 'http://127.0.0.1:8080/api/v1';
type Session = { accessToken: string; refreshToken: string };
type Evidence = { id: string; category?: string; purpose?: string; status: string; current?: boolean };
type LinkType = 'PROPRIEDADE' | 'LOCACAO' | 'AUTORIZACAO'; type Purpose = 'CRLV' | 'FOTO' | 'USO_AUTORIZADO';
type VehicleLink = { id: string; plate: string; make: string; model: string; color: string; manufacturingYear: number; modelYear: number; linkType: LinkType; validUntil?: string; status: string; version: number; evidenceComplete: boolean; documents: Evidence[] };
type Offer = { orderId: string; originCity: string; destinationCity: string; distanceMeters: number; grossAmount: number; currency: string; orderVersion: number; cancellationPolicyId: string };
type Assignment = { id: string; orderId: string; vehicleLinkId: string; status: string; acceptedAt: string; version: number };
type Address = { street: string; number: string; district: string; city: string; state: string; postalCode: string };
type TaskAddresses = { origin: Address; destination: Address };
type Custody = { id: string; orderId: string; status: string; version: number };
type PendingPosition = { assignmentId:string; sequence:number; capturedAt:string; latitude:number; longitude:number; accuracyMeters:number };
const SESSION_KEY = 'exame-perto-mobile-session';

export default function App() {
  const [session, setSession] = useState<Session | null>(null); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [birthDate, setBirthDate] = useState(''); const [status, setStatus] = useState(''); const [documents, setDocuments] = useState<Evidence[]>([]); const [vehicles, setVehicles] = useState<VehicleLink[]>([]); const [selected, setSelected] = useState<VehicleLink | null>(null);
  const [offers,setOffers]=useState<Offer[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]); const [taskAddresses,setTaskAddresses]=useState<Record<string,TaskAddresses>>({}); const [custodies,setCustodies]=useState<Record<string,Custody>>({}); const [receiptCodes,setReceiptCodes]=useState<Record<string,string>>({}); const [receiptInput,setReceiptInput]=useState<Record<string,string>>({});
  const [plate, setPlate] = useState(''); const [make, setMake] = useState(''); const [model, setModel] = useState(''); const [color, setColor] = useState(''); const [manufacturingYear, setManufacturingYear] = useState(''); const [modelYear, setModelYear] = useState(''); const [validUntil, setValidUntil] = useState('');
  const [linkType, setLinkType] = useState<LinkType>('PROPRIEDADE'); const [purpose, setPurpose] = useState<Purpose>('CRLV'); const [busy, setBusy] = useState(false);
  const [trackingOrder,setTrackingOrder]=useState<string|null>(null); const [trackingStatus,setTrackingStatus]=useState('Localização não compartilhada.'); const locationWatch=useRef<Location.LocationSubscription|null>(null); const locationBuffer=useRef<PendingPosition[]>([]); const flushing=useRef(false); const trackingOrderRef=useRef<string|null>(null);
  useEffect(()=>{void (async()=>{const saved=await SecureStore.getItemAsync(SESSION_KEY);if(!saved)return;try{const restored=await refreshSession(JSON.parse(saved));setSession(restored);await load(restored);setStatus('Sessão móvel restaurada.');}catch{await SecureStore.deleteItemAsync(SESSION_KEY);}})();},[]);
  useEffect(()=>()=>{locationWatch.current?.remove();locationWatch.current=null;locationBuffer.current=[];trackingOrderRef.current=null;},[]);
  async function keep(next:Session){setSession(next);await SecureStore.setItemAsync(SESSION_KEY,JSON.stringify(next));return next;}
  async function refreshSession(current:Session){const r=await fetch(`${API}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:current.refreshToken})});const b=await r.json();if(!r.ok){setSession(null);await SecureStore.deleteItemAsync(SESSION_KEY);throw new Error(b.message??'Sessão expirada.');}return keep(b);}
  async function api(path:string,init:RequestInit={},current=session){if(!current)throw new Error('Sessão ausente.');const send=(token:string)=>fetch(`${API}${path}`,{...init,headers:{...(init.headers??{}),Authorization:`Bearer ${token}`}});let r=await send(current.accessToken);if(r.status===401){const renewed=await refreshSession(current);r=await send(renewed.accessToken);}return r;}
  async function load(current=session){if(!current)return;const [docs,links,offerResponse,assignmentResponse]=await Promise.all([api('/me/deliverer/documents',{},current),api('/me/vehicle-links',{},current),api('/offers',{},current),api('/me/assignments',{},current)]);if(docs.ok)setDocuments(await docs.json());if(links.ok){const values=await links.json() as VehicleLink[];setVehicles(values);if(selected)setSelected(values.find(v=>v.id===selected.id)??null);}setOffers(offerResponse.ok?((await offerResponse.json()).items as Offer[]):[]);const assigned=assignmentResponse.ok?await assignmentResponse.json() as Assignment[]:[];setAssignments(assigned);if(trackingOrderRef.current&&!assigned.some(value=>value.orderId===trackingOrderRef.current&&value.status==='ATIVA'))await stopTracking('A tarefa encerrou; o compartilhamento foi interrompido.');}
  async function login(){setBusy(true);try{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,client:'MOBILE'})});const b=await r.json();if(!r.ok)throw new Error(b.message??'Não foi possível entrar.');await keep(b);await load(b);setStatus('Sessão móvel ativa.');}catch(e){Alert.alert('Não foi possível entrar',String(e));}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{await stopTracking('Sessão encerrada; localização não compartilhada.');if(session){const r=await api('/auth/logout',{method:'POST'});if(!r.ok)throw new Error('Revogação não confirmada.');}}catch{Alert.alert('Saída local concluída','A credencial foi removida deste aparelho, mas a revogação no servidor não pôde ser confirmada.');}finally{setSession(null);setDocuments([]);setVehicles([]);setOffers([]);setAssignments([]);setTaskAddresses({});setCustodies({});await SecureStore.deleteItemAsync(SESSION_KEY);setBusy(false);}}
  async function saveProfile(){setBusy(true);try{const r=await api('/me/deliverer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({birthDate})});const b=await r.json();if(!r.ok)throw new Error(b.message??'Não foi possível salvar o cadastro.');setStatus(`Cadastro ${b.status.toLowerCase()}. A aprovação profissional continua separada.`);}catch(e){Alert.alert('Cadastro não salvo',String(e));}finally{setBusy(false);}}
  async function pick(path:string,fields:Record<string,string>,message:string){const picked=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:false,type:['application/pdf','image/jpeg','image/png']});if(picked.canceled)return;const asset=picked.assets[0];const form=new FormData();Object.entries(fields).forEach(([key,value])=>form.append(key,value));form.append('file',{uri:asset.uri,name:asset.name,type:asset.mimeType??'application/octet-stream'} as any);setBusy(true);try{const r=await api(path,{method:'POST',body:form});const b=await r.json();if(!r.ok)throw new Error(b.message??'Arquivo rejeitado.');if(b.plate)setSelected(b);await load();setStatus(message);}catch(e){Alert.alert('Upload não concluído',String(e));}finally{setBusy(false);}}
  async function saveVehicle(){setBusy(true);try{const payload={plate,make,model,color,manufacturingYear:Number(manufacturingYear),modelYear:Number(modelYear),linkType,validUntil:validUntil||null};const path=selected?`/me/vehicle-links/${selected.id}?version=${selected.version}`:'/me/vehicle-links';const r=await api(path,{method:selected?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.message??'Vínculo não salvo.');setSelected(b);await load();setStatus('Vínculo salvo como pendente. Nenhuma consulta oficial foi simulada.');}catch(e){Alert.alert('Vínculo não salvo',String(e));}finally{setBusy(false);}}
  async function acceptOffer(offer:Offer){const link=vehicles.find(value=>value.status==='APROVADO'&&(!value.validUntil||value.validUntil>=new Date().toISOString().slice(0,10)));if(!link){Alert.alert('Oferta bloqueada','É necessário um vínculo de veículo aprovado e vigente.');return;}setBusy(true);try{const r=await api(`/orders/${offer.orderId}/assignment`,{method:'POST',headers:{'Content-Type':'application/json','If-Match':String(offer.orderVersion),'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({vehicleLinkId:link.id,acceptedCancellationPolicyId:offer.cancellationPolicyId})});const b=await r.json();if(!r.ok)throw new Error(b.message??'O aceite não foi confirmado.');await load();setStatus('Designação confirmada. Os endereços completos agora estão disponíveis somente nesta tarefa.');}catch(e){Alert.alert('Designação não confirmada',String(e));}finally{setBusy(false);}}
  async function openTask(assignment:Assignment){setBusy(true);try{const r=await api(`/orders/${assignment.orderId}/addresses`);const b=await r.json();if(!r.ok)throw new Error(b.message??'Endereços indisponíveis.');setTaskAddresses(current=>({...current,[assignment.orderId]:b}));}catch(e){Alert.alert('Tarefa indisponível',String(e));}finally{setBusy(false);}}
  async function custodyAction(assignment:Assignment,action:'pickup'|'start-delivery'|'deliver',body?:unknown){const current=custodies[assignment.orderId];const version=current?.version??assignment.version;setBusy(true);try{const r=await api(`/orders/${assignment.orderId}/${action}`,{method:'POST',headers:{'Content-Type':'application/json','If-Match':String(version),'Idempotency-Key':crypto.randomUUID()},body:body?JSON.stringify(body):undefined});const b=await r.json();if(!r.ok)throw new Error(b.message??'Ação de custódia bloqueada.');setCustodies(x=>({...x,[assignment.orderId]:b}));await load();setStatus(action==='pickup'?'Retirada registrada sem abrir o envelope.':action==='start-delivery'?'Deslocamento iniciado.':'Entrega comprovada pelo código do destinatário.');}catch(e){Alert.alert('Ação não confirmada',String(e));}finally{setBusy(false);}}
  async function issueCode(assignment:Assignment){setBusy(true);try{const version=custodies[assignment.orderId]?.version??assignment.version;const r=await api(`/orders/${assignment.orderId}/receipt-code`,{method:'POST',headers:{'If-Match':String(version)}});const b=await r.json();if(!r.ok)throw new Error(b.message??'Código indisponível.');setReceiptCodes(x=>({...x,[assignment.orderId]:b.code}));}catch(e){Alert.alert('Código não emitido',String(e));}finally{setBusy(false);}}
  async function flushLocations(orderId:string){if(flushing.current)return;flushing.current=true;try{while(locationBuffer.current.length&&trackingOrderRef.current===orderId){const point=locationBuffer.current[0];const encoded=JSON.stringify(point);if(encoded.length>1024){locationBuffer.current.shift();continue;}const response=await api(`/orders/${orderId}/locations`,{method:'POST',headers:{'Content-Type':'application/json'},body:encoded});if(response.ok){locationBuffer.current.shift();setTrackingStatus(`Última posição enviada às ${new Date(point.capturedAt).toLocaleTimeString('pt-BR')} · precisão ${Math.round(point.accuracyMeters)} m.`);continue;}if([401,403,404,409,422].includes(response.status)){await stopTracking('O servidor encerrou ou revogou o compartilhamento.');break;}break;}}finally{flushing.current=false;}}
  async function startTracking(assignment:Assignment){if(trackingOrderRef.current)await stopTracking('Compartilhamento anterior interrompido.');let sequence=1;try{const latest=await api(`/orders/${assignment.orderId}/locations/latest`);if(latest.ok)sequence=(await latest.json()).sequence+1;else if(latest.status===422){setTrackingStatus('Rastreamento indisponível enquanto a política de retenção não estiver aprovada.');return;}else if(latest.status!==404){setTrackingStatus('Rastreamento indisponível para esta sessão ou tarefa.');return;}}catch{setTrackingStatus('Rastreamento indisponível: não foi possível confirmar a tarefa.');return;}const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){setTrackingStatus('Localização indisponível: permissão do sistema não concedida.');return;}let next=sequence;trackingOrderRef.current=assignment.orderId;setTrackingOrder(assignment.orderId);setTrackingStatus('Permissão concedida; aguardando posição real do sistema.');locationWatch.current=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,timeInterval:15000,distanceInterval:0},position=>{if(trackingOrderRef.current!==assignment.orderId)return;const accuracy=position.coords.accuracy;if(accuracy==null)return;const point={assignmentId:assignment.id,sequence:next++,capturedAt:new Date(position.timestamp).toISOString(),latitude:position.coords.latitude,longitude:position.coords.longitude,accuracyMeters:accuracy};const cutoff=Date.now()-120000;locationBuffer.current=[...locationBuffer.current.filter(value=>Date.parse(value.capturedAt)>=cutoff),point].slice(-8);void flushLocations(assignment.orderId);});}
  async function stopTracking(message='Localização não compartilhada.'){locationWatch.current?.remove();locationWatch.current=null;locationBuffer.current=[];trackingOrderRef.current=null;setTrackingOrder(null);setTrackingStatus(message);}
  function choose(v:VehicleLink){setSelected(v);setPlate(v.plate);setMake(v.make);setModel(v.model);setColor(v.color);setManufacturingYear(String(v.manufacturingYear));setModelYear(String(v.modelYear));setLinkType(v.linkType);setValidUntil(v.validUntil??'');}
  if(!session)return <SafeAreaView><ScrollView contentContainerStyle={{padding:24,gap:12}}><Text accessibilityRole="header">Entrar como entregador</Text><TextInput accessibilityLabel="E-mail" autoCapitalize="none" value={email} onChangeText={setEmail} placeholder="E-mail"/><TextInput accessibilityLabel="Senha" secureTextEntry value={password} onChangeText={setPassword} placeholder="Senha"/><Button title={busy?'Aguarde…':'Entrar'} onPress={login} disabled={busy}/><Text>O e-mail confirmado não aprova identidade, vínculo de veículo ou habilitação profissional.</Text></ScrollView></SafeAreaView>;
  return <SafeAreaView><ScrollView contentContainerStyle={{padding:24,gap:14}}>
    <Text accessibilityRole="header">Cadastro operacional</Text><Text>{status||'Rascunho local'}</Text><Text accessibilityRole="header">Entregador</Text><TextInput accessibilityLabel="Data de nascimento" value={birthDate} onChangeText={setBirthDate} placeholder="AAAA-MM-DD"/><Button title="Salvar cadastro" onPress={saveProfile} disabled={busy||!birthDate}/><Button title="Enviar habilitação" onPress={()=>void pick('/me/deliverer/documents',{category:'HABILITACAO'},'Comprovação recebida em quarentena.')} disabled={busy}/><Button title="Enviar comprovante operacional" onPress={()=>void pick('/me/deliverer/documents',{category:'COMPROVANTE'},'Comprovante recebido em quarentena; não fotografe o conteúdo do exame.')} disabled={busy}/>{documents.map(d=><Text key={d.id}>{d.category}: {d.status}</Text>)}
    <View><Text accessibilityRole="header">Veículo e vínculo</Text><Text>O veículo pode ser próprio, alugado ou autorizado. Propriedade não é requisito universal; CRLV, fotos e a evidência aplicável permanecem privados.</Text></View>
    <TextInput accessibilityLabel="Placa" autoCapitalize="characters" value={plate} onChangeText={setPlate} placeholder="ABC1D23"/><TextInput accessibilityLabel="Marca" value={make} onChangeText={setMake} placeholder="Marca"/><TextInput accessibilityLabel="Modelo" value={model} onChangeText={setModel} placeholder="Modelo"/><TextInput accessibilityLabel="Cor" value={color} onChangeText={setColor} placeholder="Cor"/><TextInput accessibilityLabel="Ano de fabricação" inputMode="numeric" value={manufacturingYear} onChangeText={setManufacturingYear} placeholder="2024"/><TextInput accessibilityLabel="Ano do modelo" inputMode="numeric" value={modelYear} onChangeText={setModelYear} placeholder="2025"/>
    <Text>Tipo de vínculo: {linkType}</Text>{(['PROPRIEDADE','LOCACAO','AUTORIZACAO'] as LinkType[]).map(value=><Button key={value} title={value.toLocaleLowerCase('pt-BR')} onPress={()=>setLinkType(value)} disabled={busy}/>)}{linkType!=='PROPRIEDADE'&&<TextInput accessibilityLabel="Validade do vínculo" value={validUntil} onChangeText={setValidUntil} placeholder="AAAA-MM-DD"/>}<Button title={selected?'Atualizar e abrir nova revisão':'Cadastrar veículo e vínculo'} onPress={saveVehicle} disabled={busy||!plate||!make||!model||!color||!manufacturingYear||!modelYear}/>
    {vehicles.map(v=><View key={v.id} style={{gap:4,paddingVertical:8}}><Text>{v.plate} · {v.model} · {v.linkType} · {v.status}</Text><Button title="Selecionar vínculo" onPress={()=>choose(v)} disabled={busy}/>{v.documents.map(d=><Text key={`${d.id}-${d.purpose}`}>{d.purpose}: {d.status}{d.current===false?' · substituído':''}</Text>)}</View>)}
    {selected&&<View style={{gap:6}}><Text accessibilityRole="header">Documento do vínculo</Text><Text>Finalidade: {purpose}</Text>{(['CRLV','FOTO',...(linkType==='PROPRIEDADE'?[]:['USO_AUTORIZADO'])] as Purpose[]).map(value=><Button key={value} title={value.toLocaleLowerCase('pt-BR')} onPress={()=>setPurpose(value)} disabled={busy}/>)}<Button title="Selecionar e enviar arquivo" onPress={()=>void pick(`/me/vehicle-links/${selected.id}/documents`,{version:String(selected.version),purpose},'Evidência recebida em quarentena. A substituição exige nova revisão.')} disabled={busy}/><Text>Inspeção estrutural não verifica autenticidade nem substitui varredura antimalware.</Text></View>}
    <View style={{gap:8}}><Text accessibilityRole="header">Ofertas disponíveis</Text><Text>Antes do aceite, somente cidades, distância e valor são exibidos. Destinatário e endereço exato permanecem ocultos.</Text>{offers.length?offers.map(offer=><View key={offer.orderId} style={{gap:4,paddingVertical:8}}><Text>{offer.originCity} → {offer.destinationCity}</Text><Text>{offer.distanceMeters} m · {offer.currency} {offer.grossAmount}</Text><Button title="Aceitar oferta" onPress={()=>void acceptOffer(offer)} disabled={busy}/></View>):<Text>Nenhuma oferta elegível no momento.</Text>}</View>
    <View style={{gap:8}}><Text accessibilityRole="header">Minhas designações</Text><Text>{trackingStatus}</Text>{assignments.length?assignments.map(assignment=><View key={assignment.id} style={{gap:4,paddingVertical:8}}><Text>Pedido {assignment.orderId} · {assignment.status}</Text><Button title="Consultar endereços da tarefa" onPress={()=>void openTask(assignment)} disabled={busy}/>{assignment.status==='ATIVA'&&trackingOrder!==assignment.orderId&&<Button title="Compartilhar localização da tarefa" onPress={()=>void startTracking(assignment)} disabled={busy}/>} {trackingOrder===assignment.orderId&&<Button title="Parar compartilhamento de localização" onPress={()=>void stopTracking()} disabled={busy}/>} {assignment.status==='ATIVA'&&!custodies[assignment.orderId]&&<Button title="Registrar retirada (sem abrir envelope)" onPress={()=>{const proof=documents.find(d=>d.category==='COMPROVANTE'&&d.status==='INSPECAO_APROVADA');if(!proof){Alert.alert('Evidência necessária','Envie uma evidência COMPROVANTE aprovada antes da retirada.');return;}void custodyAction(assignment,'pickup',{evidenceDocumentId:proof.id});}} disabled={busy}/>}<Button title="Iniciar entrega" onPress={()=>void custodyAction(assignment,'start-delivery')} disabled={busy||custodies[assignment.orderId]?.status!=='ATIVA'}/><TextInput accessibilityLabel="Código de recebimento" secureTextEntry value={receiptInput[assignment.orderId]??''} onChangeText={v=>setReceiptInput(x=>({...x,[assignment.orderId]:v}))} placeholder="Código entregue pelo destinatário"/><Button title="Confirmar entrega" onPress={()=>void custodyAction(assignment,'deliver',{code:receiptInput[assignment.orderId]??''})} disabled={busy||!receiptInput[assignment.orderId]}/>{taskAddresses[assignment.orderId]&&<Text>Retirada: {taskAddresses[assignment.orderId].origin.street}, {taskAddresses[assignment.orderId].origin.number} — {taskAddresses[assignment.orderId].origin.city}{'\n'}Entrega: {taskAddresses[assignment.orderId].destination.street}, {taskAddresses[assignment.orderId].destination.number} — {taskAddresses[assignment.orderId].destination.city}</Text>}</View>):<Text>Nenhuma designação ativa ou histórica.</Text>}</View>
    {status&&<Text accessibilityLiveRegion="polite">{status}</Text>}<Button title="Atualizar acompanhamento" onPress={()=>void load()} disabled={busy}/><Button title="Sair" onPress={()=>void logout()} disabled={busy}/>
  </ScrollView></SafeAreaView>;
}
