import { useEffect, useState } from 'react';
import { Alert, Button, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as SecureStore from 'expo-secure-store';

const API = process.env.EXPO_PUBLIC_API_URL ?? 'http://127.0.0.1:8080/api/v1';
type Session = { accessToken: string; refreshToken: string };
type Evidence = { id: string; category: string; status: string };
const SESSION_KEY = 'exame-perto-mobile-session';

export default function App() {
  const [session, setSession] = useState<Session | null>(null);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [birthDate, setBirthDate] = useState(''); const [status, setStatus] = useState('');
  const [documents, setDocuments] = useState<Evidence[]>([]);
  const [busy, setBusy] = useState(false);
  useEffect(()=>{void (async()=>{const saved=await SecureStore.getItemAsync(SESSION_KEY);if(!saved)return;try{const restored=await refreshSession(JSON.parse(saved));setSession(restored);await loadDocuments(restored);setStatus('Sessão móvel restaurada.');}catch{await SecureStore.deleteItemAsync(SESSION_KEY);}})();},[]);
  async function keep(next:Session){setSession(next);await SecureStore.setItemAsync(SESSION_KEY,JSON.stringify(next));return next;}
  async function refreshSession(current:Session){const r=await fetch(`${API}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:current.refreshToken})});const b=await r.json();if(!r.ok){setSession(null);await SecureStore.deleteItemAsync(SESSION_KEY);throw new Error(b.message??'Sessão expirada.');}return keep(b);}
  async function api(path:string,init:RequestInit={},current=session){if(!current)throw new Error('Sessão ausente.');const send=(token:string)=>fetch(`${API}${path}`,{...init,headers:{...(init.headers??{}),Authorization:`Bearer ${token}`}});let r=await send(current.accessToken);if(r.status===401){const renewed=await refreshSession(current);r=await send(renewed.accessToken);}return r;}
  async function loadDocuments(current=session){if(!current)return;const r=await api('/me/deliverer/documents',{},current);if(r.ok)setDocuments(await r.json());}
  async function login() { setBusy(true); try { const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,client:'MOBILE'})}); const b=await r.json(); if(!r.ok) throw new Error(b.message??'Não foi possível entrar.'); await keep(b); await loadDocuments(b); setStatus('Sessão móvel ativa.'); } catch(e) { Alert.alert('Não foi possível entrar',String(e)); } finally { setBusy(false); } }
  async function logout(){setBusy(true);try{if(session){const r=await api('/auth/logout',{method:'POST'});if(!r.ok)throw new Error('Revogação não confirmada.');}}catch{Alert.alert('Saída local concluída','A credencial foi removida deste aparelho, mas a revogação no servidor não pôde ser confirmada.');}finally{setSession(null);setDocuments([]);await SecureStore.deleteItemAsync(SESSION_KEY);setBusy(false);}}
  async function saveProfile() { if(!session) return; setBusy(true); try { const r=await api('/me/deliverer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({birthDate})}); const b=await r.json(); if(!r.ok) throw new Error(b.message??'Não foi possível salvar o cadastro.'); setStatus(`Cadastro ${b.status.toLowerCase()}. Documentos ainda exigem inspeção e aprovação separadas.`); } catch(e) { Alert.alert('Cadastro não salvo',String(e)); } finally { setBusy(false); } }
  async function upload() { if(!session) return; const picked=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:false,type:['application/pdf','image/jpeg','image/png']}); if(picked.canceled) return; const asset=picked.assets[0]; const category='HABILITACAO'; const form=new FormData(); form.append('category',category); form.append('file',{uri:asset.uri,name:asset.name,type:asset.mimeType??'application/octet-stream'} as any); setBusy(true); try { const r=await api('/me/deliverer/documents',{method:'POST',body:form}); const b=await r.json(); if(!r.ok) throw new Error(b.message??'Arquivo rejeitado.'); await loadDocuments(); setStatus(`Arquivo recebido em quarentena (${b.status}). Aguarde inspeção; envio não aprova o cadastro.`); } catch(e) { Alert.alert('Upload não concluído',String(e)); } finally { setBusy(false); } }
  if(!session) return <SafeAreaView><ScrollView contentContainerStyle={{padding:24,gap:12}}><Text accessibilityRole="header">Entrar como entregador</Text><TextInput accessibilityLabel="E-mail" autoCapitalize="none" value={email} onChangeText={setEmail} placeholder="E-mail"/><TextInput accessibilityLabel="Senha" secureTextEntry value={password} onChangeText={setPassword} placeholder="Senha"/><Button title={busy?'Aguarde…':'Entrar'} onPress={login} disabled={busy}/><Text>O e-mail confirmado não aprova identidade ou habilitação profissional.</Text></ScrollView></SafeAreaView>;
  return <SafeAreaView><ScrollView contentContainerStyle={{padding:24,gap:16}}><Text accessibilityRole="header">Cadastro do entregador</Text><Text>Estado: {status||'rascunho'}</Text><TextInput accessibilityLabel="Data de nascimento" value={birthDate} onChangeText={setBirthDate} placeholder="AAAA-MM-DD"/><Button title="Salvar cadastro" onPress={saveProfile} disabled={busy||!birthDate}/><View accessible accessibilityRole="header"><Text>Comprovações privadas</Text><Text>O arquivo vai para quarentena com nome gerado. A inspeção de segurança do arquivo, a autenticidade documental e a aprovação profissional são etapas independentes.</Text></View><Button title="Enviar habilitação (PDF/JPG/PNG)" onPress={upload} disabled={busy}/><Button title="Atualizar acompanhamento" onPress={()=>void loadDocuments()} disabled={busy}/>{documents.map(d=><Text key={d.id}>{d.category}: {d.status}</Text>)}{status&&<Text accessibilityLiveRegion="polite">{status}</Text>}<Button title="Sair" onPress={()=>void logout()} disabled={busy}/></ScrollView></SafeAreaView>;
}
