import { useState } from 'react';
import { Alert, Button, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';

const API = process.env.EXPO_PUBLIC_API_URL ?? 'http://127.0.0.1:8080/api/v1';
type Session = { accessToken: string };

export default function App() {
  const [session, setSession] = useState<Session | null>(null);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [birthDate, setBirthDate] = useState(''); const [status, setStatus] = useState('');
  const [busy, setBusy] = useState(false);
  async function login() { setBusy(true); try { const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,client:'MOBILE'})}); const b=await r.json(); if(!r.ok) throw new Error(b.message??'Não foi possível entrar.'); setSession(b); setStatus('Sessão móvel ativa.'); } catch(e) { Alert.alert('Não foi possível entrar',String(e)); } finally { setBusy(false); } }
  async function saveProfile() { if(!session) return; setBusy(true); try { const r=await fetch(`${API}/me/deliverer`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.accessToken}`},body:JSON.stringify({birthDate})}); const b=await r.json(); if(!r.ok) throw new Error(b.message??'Não foi possível salvar o cadastro.'); setStatus(`Cadastro ${b.status.toLowerCase()}. Documentos ainda exigem inspeção e aprovação separadas.`); } catch(e) { Alert.alert('Cadastro não salvo',String(e)); } finally { setBusy(false); } }
  async function upload() { if(!session) return; const picked=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:false,type:['application/pdf','image/jpeg','image/png']}); if(picked.canceled) return; const asset=picked.assets[0]; const category='HABILITACAO'; const form=new FormData(); form.append('category',category); form.append('file',{uri:asset.uri,name:asset.name,type:asset.mimeType??'application/octet-stream'} as any); setBusy(true); try { const r=await fetch(`${API}/me/deliverer/documents`,{method:'POST',headers:{Authorization:`Bearer ${session.accessToken}`},body:form}); const b=await r.json(); if(!r.ok) throw new Error(b.message??'Arquivo rejeitado.'); setStatus(`Arquivo recebido em quarentena (${b.status}). Aguarde inspeção; envio não aprova o cadastro.`); } catch(e) { Alert.alert('Upload não concluído',String(e)); } finally { setBusy(false); } }
  if(!session) return <SafeAreaView><ScrollView contentContainerStyle={{padding:24,gap:12}}><Text accessibilityRole="header">Entrar como entregador</Text><TextInput accessibilityLabel="E-mail" autoCapitalize="none" value={email} onChangeText={setEmail} placeholder="E-mail"/><TextInput accessibilityLabel="Senha" secureTextEntry value={password} onChangeText={setPassword} placeholder="Senha"/><Button title={busy?'Aguarde…':'Entrar'} onPress={login} disabled={busy}/><Text>O e-mail confirmado não aprova identidade ou habilitação profissional.</Text></ScrollView></SafeAreaView>;
  return <SafeAreaView><ScrollView contentContainerStyle={{padding:24,gap:16}}><Text accessibilityRole="header">Cadastro do entregador</Text><Text>Estado: {status||'rascunho'}</Text><TextInput accessibilityLabel="Data de nascimento" value={birthDate} onChangeText={setBirthDate} placeholder="AAAA-MM-DD"/><Button title="Salvar cadastro" onPress={saveProfile} disabled={busy||!birthDate}/><View accessible accessibilityRole="header"><Text>Comprovações privadas</Text><Text>O arquivo vai para quarentena com nome gerado. A inspeção e a aprovação profissional são etapas independentes.</Text></View><Button title="Enviar habilitação (PDF/JPG/PNG)" onPress={upload} disabled={busy}/>{status&&<Text accessibilityLiveRegion="polite">{status}</Text>}</ScrollView></SafeAreaView>;
}
