package br.com.exameperto.identity;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.http.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.annotation.DirtiesContext;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.*;

@DirtiesContext @Testcontainers @SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,
 properties={"registration.privacy-approved=true","security.data-key=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","security.search-key=AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=","security.signing-key=AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI=","registration.attempts-per-minute=1000","registration.global-attempts-per-minute=5000"})
class CustodyFlowTest {
    @Container static final PostgreSQLContainer<?> DB=new PostgreSQLContainer<>("postgres:17.6");
    @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",DB::getJdbcUrl);r.add("spring.datasource.username",DB::getUsername);r.add("spring.datasource.password",DB::getPassword);}
    @LocalServerPort int port; @Autowired JdbcTemplate jdbc; @Autowired DataProtector protector; @Autowired ObjectMapper json; @MockBean PaymentProvider payments;
    HttpClient http=HttpClient.newHttpClient(); String pass="Senha-sintetica-123"; UUID tariff,cancel,policy,unit,protocol;
    @BeforeEach void policy(){tariff=UUID.randomUUID();cancel=UUID.randomUUID();policy=UUID.randomUUID();unit=UUID.randomUUID();protocol=UUID.randomUUID();int n=Math.abs(UUID.randomUUID().hashCode()%1000000)+1;jdbc.update("INSERT INTO tarifa(id,numero,formula_codigo,parametros,inicio,estado) VALUES (?,?,'BASE_KM_MINUTO','{}',clock_timestamp(),'ATIVA')",tariff,n);jdbc.update("INSERT INTO politica_cancelamento(id,numero,criterios,inicio,estado) VALUES (?,?,'{}',clock_timestamp(),'ATIVA')",cancel,n+1);jdbc.update("INSERT INTO politica_designacao(id,numero,limite_tarefas_simultaneas,inicio,estado) VALUES (?,?,2,clock_timestamp(),'ATIVA')",policy,n+2);jdbc.update("INSERT INTO protocolo_custodia(id,unidade_id,numero,regras,cobertura_retorno_confirmada,inicio,estado) VALUES (?,?,1,'{}',true,clock_timestamp(),'HABILITADO')",protocol,unit);}
    @Test void pickupDeliveryCodeAndIncidentGuardsAreAtomic() throws Exception {
        Account recipient=account("recipient"), driver=account("driver"); Driver d=driver(driver); Fixture f=fixture(recipient,driver,d);
        assertThat(request(driver,"POST","/orders/"+f.order+"/assignment",Map.of("vehicleLinkId",d.link,"acceptedCancellationPolicyId",cancel),"a","2").statusCode()).isEqualTo(201);
        assertThat(request(driver,"POST","/orders/"+f.order+"/pickup",Map.of("evidenceDocumentId",f.evidence),"p","3").statusCode()).isEqualTo(200);
        assertThat(request(driver,"POST","/orders/"+f.order+"/start-delivery",null,"s","4").statusCode()).isEqualTo(200);
        var code=request(recipient,"POST","/orders/"+f.order+"/receipt-code",null,null,"5");assertThat(code.statusCode()).isEqualTo(200);String secret=json.readTree(code.body()).get("code").asText();assertThat(request(driver,"POST","/orders/"+f.order+"/deliver",Map.of("code","wrong-code-that-is-long-enough"),"d1","5").statusCode()).isEqualTo(422);assertThat(request(driver,"POST","/orders/"+f.order+"/deliver",Map.of("code",secret),"d2","5").statusCode()).isEqualTo(200);assertThat(request(driver,"POST","/orders/"+f.order+"/deliver",Map.of("code",secret),"d3","6").statusCode()).isEqualTo(404);assertThat(jdbc.queryForObject("SELECT estado FROM pedido WHERE id=?",String.class,f.order)).isEqualTo("ENTREGUE");assertThat(jdbc.queryForObject("SELECT count(*) FROM evento_custodia WHERE pedido_id=? AND tipo='ENTREGA_COMPROVADA'",Long.class,f.order)).isEqualTo(1);
    }
    @Test void revokedRecipientAndUndesignatedDriverCannotMoveCustody() throws Exception {Account recipient=account("recipient2"),driver=account("driver2"),outsider=account("outsider");Driver d=driver(driver),o=driver(outsider);Fixture f=fixture(recipient,driver,d);assertThat(request(outsider,"POST","/orders/"+f.order+"/pickup",Map.of("evidenceDocumentId",f.evidence),"x","3").statusCode()).isEqualTo(404);assertThat(request(driver,"POST","/orders/"+f.order+"/assignment",Map.of("vehicleLinkId",d.link,"acceptedCancellationPolicyId",cancel),"a2","2").statusCode()).isEqualTo(201);assertThat(request(driver,"POST","/orders/"+f.order+"/pickup",Map.of("evidenceDocumentId",f.evidence),"p2","3").statusCode()).isEqualTo(200);assertThat(request(driver,"POST","/orders/"+f.order+"/incidents",Map.of("type","LACRE_COMPROMETIDO","description","lacrado externo"),"i","4").statusCode()).isEqualTo(201);assertThat(jdbc.queryForObject("SELECT estado FROM pedido WHERE id=?",String.class,f.order)).isEqualTo("OCORRENCIA");assertThat(request(driver,"POST","/orders/"+f.order+"/start-delivery",null,"s2","5").statusCode()).isEqualTo(409);}
    private Fixture fixture(Account recipient,Account driver,Driver d){UUID patient=patient(recipient),authDoc=doc(recipient.user,"AUTORIZACAO_RETIRADA","QUARENTENA"),evidence=doc(driver.user,"COMPROVANTE","INSPECAO_APROVADA"),order=UUID.randomUUID(),quote=UUID.randomUUID(),acceptance=UUID.randomUUID(),auth=UUID.randomUUID();byte[] blob=protect(Map.of("street","Rua", "number","1", "district","Centro", "city","Cidade", "state","SP", "postalCode","01001000", "latitude",-23.5,"longitude",-46.6));jdbc.update("INSERT INTO pedido(id,paciente_id,solicitante_id,origem_cifrada,destino_cifrada,origem_lat,origem_lon,destino_lat,destino_lon,destinatario_id,unidade_id,protocolo_id,estado,version) VALUES (?,?,?,?,?,-23.5,-46.6,-23.4,-46.5,?,?,?,'DISPONIVEL',2)",order,patient,recipient.user,blob,blob,recipient.user,unit,protocol);jdbc.update("INSERT INTO autorizacao_retirada(id,pedido_id,documento_id,estado,criada_por,valida_ate) VALUES (?,?,?,'VERIFICADA',?,clock_timestamp()+interval '1 day')",auth,order,authDoc,recipient.user);jdbc.update("INSERT INTO orcamento(id,pedido_id,paciente_id,tarifa_id,rota_provedor,rota_referencia,distancia_m,duracao_s,rota_calculada_em,transito_incluido,politica_snapshot,frete,paciente_valor,subsidio_valor,moeda,expira_em,aceito_em,estado,politica_cancelamento_id,pedido_version,version) VALUES (?,?,?,?,'test','ref',100,60,clock_timestamp(),false,'{}',10,10,0,'BRL',clock_timestamp()+interval '1 hour',clock_timestamp(),'ACEITO',?,1,1)",quote,order,patient,tariff,cancel);jdbc.update("INSERT INTO aceite_orcamento(id,orcamento_id,pedido_id,paciente_id,aceito_por,pedido_version,orcamento_version,condicoes_snapshot,frete,paciente_valor,subsidio_valor,moeda) VALUES (?,?,?,?,?,1,1,'{}',10,10,0,'BRL')",acceptance,quote,order,patient,recipient.user);jdbc.update("INSERT INTO operacao_financeira(id,pedido_id,tipo,chave_negocio,valor,moeda,estado,provedor,beneficiario_referencia) VALUES (?,?,'COBRANCA',?,10,'BRL','CONFIRMADA','test',?)",UUID.randomUUID(),order,"charge:"+order,recipient.user);return new Fixture(order,evidence);}
    private Account account(String p){UUID id=UUID.randomUUID();String email=p+id+"@example.test";jdbc.update("INSERT INTO usuario(id,email_cifrado,email_busca,senha_hash,nome_cifrado,estado,email_verificado_em) VALUES (?,?,?,?,?,'ATIVO',clock_timestamp())",id,protector.encrypt(email),protector.lookup(email),Passwords.hash(pass),protector.encrypt(p));try{var r=request(null,"POST","/auth/login",Map.of("email",email,"password",pass,"client","MOBILE"),null,null);return new Account(id,json.readTree(r.body()).get("accessToken").asText());}catch(Exception e){throw new RuntimeException(e);}}
    private Driver driver(Account a){UUID dr=UUID.randomUUID(),vehicle=UUID.randomUUID(),link=UUID.randomUUID(),photo=doc(a.user,"FOTO_OPERACIONAL","INSPECAO_APROVADA");String plate="ABC"+Math.abs(UUID.randomUUID().hashCode()%10000);jdbc.update("INSERT INTO entregador(id,usuario_id,nascimento,estado,foto_aprovada_id) VALUES (?,?,DATE '1990-01-01','APROVADO',?)",dr,a.user,photo);jdbc.update("INSERT INTO veiculo(id,placa,marca,modelo,cor,ano_fabricacao,ano_modelo,estado) VALUES (?,?,'M','M','A',2024,2024,'APROVADO')",vehicle,plate);jdbc.update("INSERT INTO vinculo_veiculo(id,entregador_id,veiculo_id,tipo,estado,valido_ate,version) VALUES (?,?,?,'PROPRIEDADE','APROVADO',current_date+10,1)",link,dr,vehicle);return new Driver(dr,link);}
    private UUID patient(Account a){UUID id=UUID.randomUUID();String cpf=String.format("%011d",Math.abs(id.hashCode()));jdbc.update("INSERT INTO paciente(id,usuario_id,cpf_cifrado,cpf_busca,nascimento,identidade_estado) VALUES (?,?,?,?,DATE '1980-01-01','VERIFICADA')",id,a.user,protector.encrypt(cpf),protector.lookup(cpf));return id;}
    private UUID doc(UUID owner,String cat,String state){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO documento(id,proprietario_id,categoria,objeto_chave,sha256,mime,tamanho,estado) VALUES (?, ?, ?, ?, '12345678901234567890123456789012','application/octet-stream',100,?)",id,owner,cat,"test/"+id,state);return id;}
    private byte[] protect(Object v){try{return protector.encrypt(json.writeValueAsString(v));}catch(Exception e){throw new RuntimeException(e);}}
    private HttpResponse<String> request(Account a,String method,String path,Object body,String key,String version)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).header("Content-Type","application/json");if(a!=null)b.header("Authorization","Bearer "+a.token);if(key!=null)b.header("Idempotency-Key",key);if(version!=null)b.header("If-Match",version);return http.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());}
    record Account(UUID user,String token){} record Driver(UUID driver,UUID link){} record Fixture(UUID order,UUID evidence){}
}
