package br.com.exameperto.identity;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.http.*;
import java.nio.ByteBuffer;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@org.springframework.test.annotation.DirtiesContext
@Testcontainers
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"registration.privacy-approved=true","registration.allowed-origin=http://localhost:5173","security.data-key=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","security.search-key=AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=","security.signing-key=AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI=","registration.attempts-per-minute=1000","registration.global-attempts-per-minute=5000","tracking.enabled=true"})
class TrackingFlowTest {
    @Container static final PostgreSQLContainer<?> DB=new PostgreSQLContainer<>("postgres:17.6");
    @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",DB::getJdbcUrl);r.add("spring.datasource.username",DB::getUsername);r.add("spring.datasource.password",DB::getPassword);}
    @LocalServerPort int port; @Autowired JdbcTemplate jdbc; @Autowired DataProtector protector; @Autowired ObjectMapper json; @Autowired TrackingLiveRegistry live;
    HttpClient http=HttpClient.newHttpClient(); final String password="Senha-sintetica-123"; UUID tariff,cancel,assignmentPolicy;
    @BeforeEach void policies(){int n=Math.abs(UUID.randomUUID().hashCode()%1000000)+100;tariff=UUID.randomUUID();cancel=UUID.randomUUID();assignmentPolicy=UUID.randomUUID();jdbc.update("INSERT INTO tarifa(id,numero,formula_codigo,parametros,inicio,estado) VALUES (?,?,'BASE_KM_MINUTO','{}',clock_timestamp(),'ATIVA')",tariff,n);jdbc.update("INSERT INTO politica_cancelamento(id,numero,criterios,inicio,estado) VALUES (?,?,'{}',clock_timestamp(),'ATIVA')",cancel,n+1);jdbc.update("INSERT INTO politica_designacao(id,numero,limite_tarefas_simultaneas,inicio,estado) VALUES (?,?,3,clock_timestamp(),'ATIVA')",assignmentPolicy,n+2);}

    @Test void httpRejectsInvalidDuplicateOutOfOrderAndRateLimitedPositions() throws Exception {
        Account patient=account("tracking-patient"),driverAccount=account("tracking-driver"),outsider=account("tracking-outsider");Fixture f=fixture(patient,driverAccount);
        assertThat(request(patient,"GET","/orders/"+f.order+"/locations/latest",null).statusCode()).isEqualTo(404);
        Instant base=Instant.now().minusSeconds(20);Map<String,Object> first=point(f.assignment,1,base,-23.550520,-46.633308,12.50);
        assertThat(send(outsider,f.order,first).statusCode()).isEqualTo(404);
        assertThat(requestRaw(driverAccount,"POST","/orders/"+f.order+"/locations",json.writeValueAsString(first)+" ".repeat(1025)).statusCode()).isEqualTo(413);
        assertThat(send(driverAccount,f.order,point(f.assignment,1,base,91,-46,10)).statusCode()).isEqualTo(400);
        assertThat(send(driverAccount,f.order,point(f.assignment,1,Instant.now().minusSeconds(121),-23,-46,10)).statusCode()).isEqualTo(422);
        assertThat(send(driverAccount,f.order,point(f.assignment,1,Instant.now().plusSeconds(31),-23,-46,10)).statusCode()).isEqualTo(422);
        assertThat(send(driverAccount,f.order,first).statusCode()).isEqualTo(201);
        assertThat(send(driverAccount,f.order,first).statusCode()).isEqualTo(200);
        assertThat(send(driverAccount,f.order,point(f.assignment,1,base,-22,-46,12.5)).statusCode()).isEqualTo(409);
        HttpResponse<String> lowAccuracy=send(driverAccount,f.order,point(f.assignment,2,base.plusSeconds(2),-23.55,-46.63,150));assertThat(lowAccuracy.statusCode()).isEqualTo(201);assertThat(json.readTree(lowAccuracy.body()).get("lowAccuracy").asBoolean()).isTrue();
        assertThat(send(driverAccount,f.order,point(f.assignment,3,base.plusSeconds(1),-23.54,-46.62,10)).statusCode()).isEqualTo(422);
        for(int sequence=3;sequence<=8;sequence++)assertThat(send(driverAccount,f.order,point(f.assignment,sequence,base.plusSeconds(sequence),-23.55,-46.63,10)).statusCode()).isEqualTo(201);
        assertThat(send(driverAccount,f.order,first).statusCode()).isEqualTo(200);
        assertThat(send(driverAccount,f.order,point(f.assignment,9,base.plusSeconds(9),-23.55,-46.63,10)).statusCode()).isEqualTo(429);
        HttpResponse<String> latest=request(patient,"GET","/orders/"+f.order+"/locations/latest",null);assertThat(latest.statusCode()).withFailMessage(latest.body()).isEqualTo(200);JsonNode view=json.readTree(latest.body());assertThat(view.get("sequence").asLong()).isEqualTo(8);assertThat(view.get("stale").asBoolean()).isFalse();assertThat(jdbc.queryForObject("SELECT count(*) FROM posicao_tarefa WHERE pedido_id=?",Long.class,f.order)).isEqualTo(8);
        jdbc.update("UPDATE posicao_tarefa SET capturada_em=capturada_em-interval '2 minutes' WHERE pedido_id=?",f.order);assertThat(json.readTree(request(patient,"GET","/orders/"+f.order+"/locations/latest",null).body()).get("stale").asBoolean()).isTrue();
        jdbc.update("UPDATE designacao SET encerrada_em=clock_timestamp() WHERE id=?",f.assignment);jdbc.update("UPDATE pedido SET estado='ENTREGUE' WHERE id=?",f.order);
        assertThat(request(patient,"GET","/orders/"+f.order+"/locations/latest",null).statusCode()).isEqualTo(404);assertThat(send(driverAccount,f.order,point(f.assignment,9,Instant.now(),-23,-46,10)).statusCode()).isEqualTo(404);
    }

    @Test void websocketRevalidatesOpenConnectionsAfterRevocationLogoutAndExpiry() throws Exception {
        Account patient=account("ws-patient"),driver=account("ws-driver"),family=account("ws-family"),noScope=account("ws-no-scope"),outsider=account("ws-outsider");Fixture f=fixture(patient,driver);UUID grant=grant(patient,f.patient,family,true);grant(patient,f.patient,noScope,false);
        try(StompSocket patientSocket=connect(patient.token);StompSocket familySocket=connect(family.token);StompSocket noScopeSocket=connect(noScope.token);StompSocket outsiderSocket=connect(outsider.token);StompSocket wildcardSocket=connect(patient.token)){
            patientSocket.subscribe(f.order);familySocket.subscribe(f.order);noScopeSocket.subscribe(f.order);outsiderSocket.subscribe(f.order);Thread.sleep(300);
            wildcardSocket.send("SUBSCRIBE\nid:wildcard\ndestination:/user/queue/orders/*/locations\nack:auto\n\n\0");assertThat(wildcardSocket.awaitPrefix("ERROR",2)).isNotNull();
            assertThat(send(driver,f.order,point(f.assignment,1,Instant.now().minusSeconds(2),-23.55,-46.63,25)).statusCode()).isEqualTo(201);
            assertThat(patientSocket.awaitPrefix("MESSAGE",3)).contains("\"sequence\":1");assertThat(familySocket.awaitPrefix("MESSAGE",3)).contains("\"sequence\":1");assertThat(noScopeSocket.awaitPrefix("MESSAGE",1)).isNull();assertThat(outsiderSocket.awaitPrefix("MESSAGE",1)).isNull();
            jdbc.update("UPDATE autorizacao_paciente SET revogada_em=clock_timestamp() WHERE id=?",grant);
            assertThat(send(driver,f.order,point(f.assignment,2,Instant.now().minusSeconds(1),-23.54,-46.62,30)).statusCode()).isEqualTo(201);
            assertThat(patientSocket.awaitPrefix("MESSAGE",3)).contains("\"sequence\":2");assertThat(familySocket.awaitPrefix("MESSAGE",1)).isNull();
            assertThat(request(patient,"POST","/auth/logout",Map.of()).statusCode()).isEqualTo(204);
            assertThat(send(driver,f.order,point(f.assignment,3,Instant.now(),-23.53,-46.61,35)).statusCode()).isEqualTo(201);assertThat(patientSocket.awaitPrefix("MESSAGE",1)).isNull();
        }
        Account expiring=account("ws-expiring");UUID expiringGrant=grant(patient,f.patient,expiring,true);try(StompSocket socket=connect(expiring.token)){socket.subscribe(f.order);Thread.sleep(200);jdbc.update("UPDATE sessao SET access_expira_em=clock_timestamp()-interval '1 second' WHERE id=?",expiring.session);assertThat(send(driver,f.order,point(f.assignment,4,Instant.now(),-23.52,-46.60,40)).statusCode()).isEqualTo(201);assertThat(socket.awaitPrefix("MESSAGE",1)).isNull();}jdbc.update("UPDATE autorizacao_paciente SET revogada_em=clock_timestamp() WHERE id=?",expiringGrant);
        Account closing=account("ws-closing");grant(patient,f.patient,closing,true);try(StompSocket socket=connect(closing.token)){socket.subscribe(f.order);Thread.sleep(200);jdbc.update("UPDATE designacao SET encerrada_em=clock_timestamp() WHERE id=?",f.assignment);jdbc.update("UPDATE pedido SET estado='ENTREGUE' WHERE id=?",f.order);assertThat(send(driver,f.order,point(f.assignment,5,Instant.now(),-23.51,-46.59,45)).statusCode()).isEqualTo(404);live.publish(f.order,new LocationView(f.assignment,5,Instant.now(),Instant.now(),java.math.BigDecimal.valueOf(-23.51),java.math.BigDecimal.valueOf(-46.59),java.math.BigDecimal.valueOf(45),false,false));assertThat(socket.awaitPrefix("MESSAGE",1)).isNull();}
    }

    private StompSocket connect(String token)throws Exception{StompSocket listener=new StompSocket();listener.socket=http.newWebSocketBuilder().subprotocols("v12.stomp").buildAsync(URI.create("ws://127.0.0.1:"+port+"/ws"),listener).get(5,TimeUnit.SECONDS);listener.send("CONNECT\naccept-version:1.2\nAuthorization:Bearer "+token+"\nheart-beat:0,0\n\n\0");assertThat(listener.awaitPrefix("CONNECTED",5)).isNotNull();return listener;}
    private HttpResponse<String> send(Account account,UUID order,Object body)throws Exception{return request(account,"POST","/orders/"+order+"/locations",body);}
    private HttpResponse<String> request(Account account,String method,String path,Object body)throws Exception{HttpRequest.Builder builder=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).header("Authorization","Bearer "+account.token).header("Content-Type","application/json");return http.send(builder.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());}
    private HttpResponse<String> requestRaw(Account account,String method,String path,String body)throws Exception{HttpRequest request=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).header("Authorization","Bearer "+account.token).header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(body)).build();return http.send(request,HttpResponse.BodyHandlers.ofString());}
    private Map<String,Object> point(UUID assignment,long sequence,Instant captured,double lat,double lon,double accuracy){return Map.of("assignmentId",assignment,"sequence",sequence,"capturedAt",captured.toString(),"latitude",lat,"longitude",lon,"accuracyMeters",accuracy);}
    private Fixture fixture(Account patientAccount,Account driverAccount){UUID patient=patient(patientAccount),driver=UUID.randomUUID(),vehicle=UUID.randomUUID(),link=UUID.randomUUID(),photo=document(driverAccount.id,"FOTO_OPERACIONAL","INSPECAO_APROVADA"),order=UUID.randomUUID(),quote=UUID.randomUUID(),assignment=UUID.randomUUID(),unit=UUID.randomUUID();jdbc.update("INSERT INTO entregador(id,usuario_id,nascimento,estado,foto_aprovada_id) VALUES (?,?,DATE '1990-01-01','APROVADO',?)",driver,driverAccount.id,photo);jdbc.update("INSERT INTO veiculo(id,placa,marca,modelo,cor,ano_fabricacao,ano_modelo,estado) VALUES (?,?,?,?,?,2024,2025,'APROVADO')",vehicle,"TRK"+Math.abs(order.hashCode()%10000),"Marca","Modelo","Azul");jdbc.update("INSERT INTO vinculo_veiculo(id,entregador_id,veiculo_id,tipo,estado,valido_ate,version) VALUES (?,?,?,'PROPRIEDADE','APROVADO',current_date+10,1)",link,driver,vehicle);byte[] address=protector.encrypt("{\"street\":\"Rua sintética\",\"number\":\"10\",\"district\":\"Centro\",\"city\":\"Cidade\",\"state\":\"SP\",\"postalCode\":\"01001000\",\"latitude\":-23.55,\"longitude\":-46.63}");jdbc.update("INSERT INTO pedido(id,paciente_id,solicitante_id,origem_cifrada,destino_cifrada,origem_lat,origem_lon,destino_lat,destino_lon,destinatario_id,unidade_id,estado,version) VALUES (?,?,?,?,?,-23.55,-46.63,-23.54,-46.62,?,?,'ACEITA',3)",order,patient,patientAccount.id,address,address,patientAccount.id,unit);jdbc.update("INSERT INTO orcamento(id,pedido_id,paciente_id,tarifa_id,rota_provedor,rota_referencia,distancia_m,duracao_s,rota_calculada_em,transito_incluido,politica_snapshot,frete,paciente_valor,subsidio_valor,moeda,expira_em,aceito_em,estado,politica_cancelamento_id,pedido_version) VALUES (?,?,?,?,'controlled','tracking',1000,300,clock_timestamp(),false,'{}',38,38,0,'BRL',clock_timestamp()+interval '1 hour',clock_timestamp(),'ACEITO',?,2)",quote,order,patient,tariff,cancel);jdbc.update("INSERT INTO designacao(id,pedido_id,entregador_id,vinculo_id,orcamento_id,politica_designacao_id,politica_cancelamento_id,pedido_version,limite_tarefas_snapshot,identificacao_snapshot) VALUES (?,?,?,?,?,?,?,?,3,'{}')",assignment,order,driver,link,quote,assignmentPolicy,cancel,2);return new Fixture(patient,order,assignment);}
    private UUID grant(Account owner,UUID patient,Account family,boolean trackingScope){UUID invitation=UUID.randomUUID(),grant=UUID.randomUUID();jdbc.update("INSERT INTO convite_familiar(id,paciente_id,destinatario_email_busca,token_hash,estado,expira_em,consumido_em,aceito_por,aceito_em,confirmado_em) VALUES (?,?,?,?,'CONFIRMADO',clock_timestamp()+interval '1 day',clock_timestamp(),?,clock_timestamp(),clock_timestamp())",invitation,patient,protector.lookup(family.email),protector.tokenHash(protector.token()),family.id);jdbc.update("INSERT INTO autorizacao_paciente(id,paciente_id,familiar_id,concedida_por,convite_id,confirmada_em,expira_em) VALUES (?,?,?,?,?,clock_timestamp(),clock_timestamp()+interval '1 day')",grant,patient,family.id,owner.id,invitation);jdbc.update("INSERT INTO autorizacao_escopo(autorizacao_id,escopo) VALUES (?,?)",grant,trackingScope?"RASTREAMENTO":"PEDIDOS");return grant;}
    private Account account(String prefix){try{UUID id=UUID.randomUUID();String email=prefix+"-"+id+"@example.test";jdbc.update("INSERT INTO usuario(id,email_cifrado,email_busca,senha_hash,nome_cifrado,estado,email_verificado_em) VALUES (?,?,?,?,?,'ATIVO',clock_timestamp())",id,protector.encrypt(email),protector.lookup(email),Passwords.hash(password),protector.encrypt(prefix));HttpRequest request=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1/auth/login")).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(Map.of("email",email,"password",password,"client","MOBILE")))).build();JsonNode body=json.readTree(http.send(request,HttpResponse.BodyHandlers.ofString()).body());String token=body.get("accessToken").asText();UUID session=jdbc.queryForObject("SELECT id FROM sessao WHERE usuario_id=? ORDER BY created_at DESC LIMIT 1",UUID.class,id);return new Account(id,email,token,session);}catch(Exception ex){throw new RuntimeException(ex);}}
    private UUID patient(Account account){UUID id=UUID.randomUUID();String cpf=String.format("%011d",Integer.toUnsignedLong(id.hashCode()));jdbc.update("INSERT INTO paciente(id,usuario_id,cpf_cifrado,cpf_busca,nascimento,identidade_estado) VALUES (?,?,?,?,DATE '1980-01-01','VERIFICADA')",id,account.id,protector.encrypt(cpf),protector.lookup(cpf));return id;}
    private UUID document(UUID owner,String category,String state){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO documento(id,proprietario_id,categoria,objeto_chave,sha256,mime,tamanho,estado) VALUES (?,?,?,?,'12345678901234567890123456789012','application/octet-stream',100,?)",id,owner,category,"synthetic/"+id,state);return id;}
    record Account(UUID id,String email,String token,UUID session){} record Fixture(UUID patient,UUID order,UUID assignment){}

    static final class StompSocket implements WebSocket.Listener,AutoCloseable {WebSocket socket;StringBuilder partial=new StringBuilder();BlockingQueue<String> frames=new LinkedBlockingQueue<>();public CompletionStage<?> onText(WebSocket ws,CharSequence data,boolean last){partial.append(data);if(last){String all=partial.toString();partial.setLength(0);for(String frame:all.split("\\u0000"))if(!frame.isBlank())frames.offer(frame);}ws.request(1);return null;}public void onOpen(WebSocket ws){ws.request(1);}void send(String value){socket.sendText(value,true).join();}String subscribe(UUID order)throws InterruptedException{return subscribeDestination("/user/queue/orders/"+order+"/locations");}String subscribeDestination(String destination)throws InterruptedException{send("SUBSCRIBE\nid:"+UUID.randomUUID()+"\nreceipt:sub\ndestination:"+destination+"\nack:auto\n\n\0");return awaitPrefix("RECEIPT",2);}String awaitPrefix(String prefix,int seconds)throws InterruptedException{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(seconds);while(System.nanoTime()<end){String value=frames.poll(100,TimeUnit.MILLISECONDS);if(value!=null&&value.startsWith(prefix))return value;}return null;}public void close(){if(socket!=null)socket.sendClose(WebSocket.NORMAL_CLOSURE,"done");}}
}
